### ISSUE TITLE
don't support large file

### ISSUE THREAD

**Issue by mfdeveloper508** [moov-io/metro2#112]
Metro2 Version: ``

**What were you trying to do?**

Used http service with large file

**What did you expect to see?**

want to use large metro file

**What did you see?**

**How can we reproduce the problem?**

http server returns error response when trying to validate a large ( 63MB / ~140k lines) txt based metro2 file.

**Comment by adamdecaf** [comment]
@mfdeveloper508 any progress?

**Comment by mfdeveloper508** [comment]
sorry, the issue fixed already
