### ISSUE TITLE
Example validation file doesn't pass validation

### ISSUE THREAD

**Issue by purplehat7** [moov-io/metro2#120]
Metro2 Version: `moov/metro2:latest` docker image as of this writing (apparently v0.4.1)

**What were you trying to do?**

Validate the example file using the same commands in the README

**What did you expect to see?**

`valid file`

**What did you see?**

``total_social_numbers_all_segments in trailer record has an invalid value``

**How can we reproduce the problem?**

By following the steps in the README:

```
docker pull moov/metro2:latest
docker run -p 8080:8080 moov/metro2:latest
```

...then, from the root of this repo (on commit `53a5e86`, the tip of `master` as of this writing):

```
curl -X POST --form "file=@./test/testdata/packed_file.json" http://localhost:8080/validator
```

**Comment by adamdecaf** [comment]
cc @mfdeveloper508 could you look at this?

**Comment by mfdeveloper508** [comment]
I will check again

**Comment by mfdeveloper508** [comment]
I tested source code and docker file too, the file is correct 
![error](https://user-images.githubusercontent.com/52543837/192015648-4467d711-b078-46ea-b140-381bec3ad70a.PNG)

But docker image of docker hub is not updated
we need to check Docker Push logic again

**Comment by adamdecaf** [comment]
I can cut a release of metro2.

**Comment by adamdecaf** [comment]
[v0.5.0](https://github.com/moov-io/metro2/releases/tag/v0.5.0) has been released. Can you try it out @purplehat7 ? Thanks for opening an issue!
