### ISSUE TITLE
useless replace directive in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [moov-io/metro2#139]
It seems that `moov-io/metro2` does not depend on `github.com/gogo/protobuf` any more, both directly and indirectly. 
So, replace directive left in go.mod makes no sense. Should it be dropped?
```txt
$ go mod why github.com/gogo/protobuf
# github.com/gogo/protobuf
(main module does not need package github.com/gogo/protobuf)
```
<https://github.com/moov-io/metro2/blob/master/go.mod#L5>
```txt
replace github.com/gogo/protobuf => github.com/gogo/protobuf v1.3.2
```

**Comment by adamdecaf** [comment]
Yep thanks!
