### ISSUE TITLE
Add fuzzer for parsing / reading

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/metro2#19]
Fuzzing is a technique for sending arbitrary input into functions to see what happens. Typically this is done to weed out crashes/panics from software, or to detect bugs. In some cases all possible inputs are ran into the program (i.e. if a function accepts 16-bit integers it's trivial to try them all).

We should support fuzzing and ship a docker image that can be ran which will help automate fuzzing. There are examples we can use from moov-io/ach:
- Fuzzing setup [from moov-io/ach](https://github.com/moov-io/ach/tree/master/test/fuzz-reader)
- [Self-Contained Dockerfile for Fuzzing](https://github.com/moov-io/ach/blob/master/Dockerfile-fuzz)

**Comment by mfdeveloper508** [comment]
https://github.com/moov-io/metro2/pull/23
