### ISSUE TITLE
Create OpenAPI specification for HTTP routes

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/metro2#21]
We should generate an [OpenAPI specification](https://swagger.io/specification/) for this project's HTTP server. This allows us better documentation and to generate clients in other languages.

Useful Editor: https://editor.swagger.io/
Example: https://github.com/moov-io/ach/blob/master/openapi.yaml

**Comment by mfdeveloper508** [comment]
https://github.com/moov-io/metro2/pull/25
