### ISSUE TITLE
Unpacked Metro2 File Print Error

### ISSUE THREAD

**Issue by VinLucero** [moov-io/metro2#36]
Metro2 Version: `v0.2.6`

**What were you trying to do?**
go run ./cmd/metro2/ print an unpacked file.

![image](https://user-images.githubusercontent.com/3068574/98280382-2eec1280-1f50-11eb-9d6c-4ef0fb99ae60.png)

**What did you expect to see?**
A printed out version of an unpacked file.

**What did you see?**
Error, without verbose explanation of the issue.

**How can we reproduce the problem?**
Attempt to Go Run Metro2 Print an unpacked file using:

go run ./cmd/metro2/ print on the unpacked_fixed_file.dat in testdata folder with format output as JSON.

**Comment by adamdecaf** [comment]
Was this addressed in slack? Anything to update in our docs or examples?
