### ISSUE TITLE
A guide on how to use the metro2 library would be very helpful

### ISSUE THREAD

**Issue by dangdennis** [moov-io/metro2#57]
Metro2 Version: `0.3.1`

**What were you trying to do?**

I wanted to use the library.

**What did you expect to see?**

I expected some reference explaining that the main library usage starts at `"github.com/moov-io/metro2/pkg/file"`
with `file.CreateFile`.

**What did you see?**

Instead, I had to dig into the CLI and API packages to learn how the metro2 lib was actually used.

**How can we reproduce the problem?**

**Comment by adamdecaf** [comment]
We've got an API guide being edited currently, but a guide over the Go functions makes sense. We'll add it to our list. /cc @nlakritz

**Comment by mfdeveloper508** [comment]
@nlakritz can you review the document?
