### ISSUE TITLE
Phone numbers with length greater than 10 do not fit inside an int32

### ISSUE THREAD

**Issue by dangdennis** [moov-io/metro2#58]
Metro2 Version: 0.3.1

**What were you trying to do?**

I was trying to create a metro2 file with a phone number of digits greater than 10.

Are we supposed to ignore the US +1 code in phone numbers when reporting to the bureaus? Does the metro2 standard only accept 10-digit phone numbers?

Our API system includes the US +1 code with phone numbers. Example: 1-XXX-XXX-XXXX. The metro2 lib uses an int32 and assumes that all phone numbers are at most 10 digits. int32 doesn't support a number greater than 10 digits. The easiest solution is to truncate our phone numbers down to just 10 digits.

**What did you expect to see?**

I guess I expected that we support phone numbers with the country extension, so an int64 is required.

**What did you see?**

A runtime error.

**How can we reproduce the problem?**

Try `15103334444` in place of any of the required phone number fields like the reporter or primary customer phone.

**Comment by dangdennis** [comment]
This answers it. Length 10 only
<img width="911" alt="Screen Shot 2021-06-03 at 11 30 02 PM" src="https://user-images.githubusercontent.com/22418429/120741781-ac1a3e80-c4c3-11eb-9c10-f85d9cf50b65.png">

**Comment by dangdennis** [comment]
Actually, the lib can't handle an 5555555555 as a phone number. While that isn't a valid number, should we use strings instead for phone numbers?

**Comment by adamdecaf** [comment]
Most likely. int32 only covers part of the space since ~4 billion can't cover phone numbers starting with 5-9.

**Comment by adamdecaf** [comment]
@dangdennis Are you using the generated Go client? I noticed that's using int32 by mistake. Can you look at https://github.com/moov-io/metro2/pull/61 and see if it helps?

**Comment by adamdecaf** [comment]
@dangdennis can you checkout v0.3.2 when you have a chance? Let us know if you run into issues. Thanks!

https://github.com/moov-io/metro2/releases/tag/v0.3.2
