### ISSUE TITLE
Conversion doesn't work properly

### ISSUE THREAD

**Issue by pushvv** [moov-io/metro2#87]
Metro2 Version: `0.3.3`

**What were you trying to do?**
I am trying to generate a json and convert it into metro.
This is the json
`{
  "header": {
    "recordDescriptorWord": 426,
    "recordIdentifier": "HEADER",
    "equifaxProgramIdentifier": "5555555555",
    "transUnionProgramIdentifier": "6666666666",
    "activityDate": "2022-01-20T18:35:42.648+03:00",
    "dateCreated": "2022-01-20T18:35:42.648+03:00",
    "programDate": "2022-01-20T18:35:42.648+03:00",
    "programRevisionDate": "2022-01-20T18:35:42.648+03:00",
    "reporterName": "name",
    "reporterAddress": "Reporter address",
    "reporterTelephoneNumber": 19999999999
  },
  "data": [
    {
      "base": {
        "recordDescriptorWord": 730,
        "processingIndicator": 1,
        "timeStamp": "2022-01-20T18:35:42.648+03:00",
        "identificationNumber": "unknown",
        "consumerAccountNumber": "L21350000010",
        "portfolioType": "I",
        "accountType": "01",
        "dateOpened": "2021-12-16T11:35:24.854+03:00",
        "highestCredit": 100,
        "termsDuration": "3",
        "termsFrequency": "M",
        "scheduledMonthlyPaymentAmount": 34,
        "actualPaymentAmount": 0,
        "accountStatus": "11",
        "paymentRating": "0",
        "paymentHistoryProfile": "0",
        "currentBalance": 104,
        "amountPastDue": 0,
        "dateAccountInformation": "2022-01-20T15:35:39.051+03:00",
        "surname": "surname",
        "firstName": "name",
        "socialSecurityNumber": 1111,
        "dateBirth": "1963-03-28T00:00:00+03:00",
        "ecoaCode": "1",
        "countryCode": "US",
        "firstLineAddress": "add",
        "secondLineAddress": "",
        "city": "cc",
        "state": "TX",
        "zipCode": "78249",
        "addressIndicator": "Y"
      },
      "j1": [],
      "j2": []
    }
  ],
  "trailer": {
    "recordDescriptorWord": 426,
    "recordIdentifier": "TRAILER",
    "totalBaseRecords": 0,
    "totalStatusCodeDF": 0,
    "totalConsumerSegmentsJ1": 0,
    "totalConsumerSegmentsJ2": 0,
    "blockCount": 0,
    "totalStatusCodeDA": 0,
    "totalStatusCode05": 0,
    "totalStatusCode11": 0,
    "totalStatusCode13": 0,
    "totalStatusCode61": 0,
    "totalStatusCode62": 0,
    "totalStatusCode63": 0,
    "totalStatusCode64": 0,
    "totalStatusCode65": 0,
    "totalStatusCode71": 0,
    "totalStatusCode78": 0,
    "totalStatusCode80": 0,
    "totalStatusCode82": 0,
    "totalStatusCode83": 0,
    "totalStatusCode84": 0,
    "totalStatusCode88": 0,
    "totalStatusCode89": 0,
    "totalStatusCode93": 0,
    "totalStatusCode94": 0,
    "totalStatusCode95": 0,
    "totalStatusCode96": 0,
    "totalStatusCode97": 0,
    "totalECOACodeZ": 0,
    "totalEmploymentSegments": 0,
    "totalOriginalCreditorSegments": 0,
    "totalPurchasedToSegments": 0,
    "totalMortgageInformationSegments": 0,
    "totalPaymentInformationSegments": 0,
    "totalChangeSegments": 0,
    "totalSocialNumbersAllSegments": 0,
    "totalSocialNumbersBaseSegments": 0,
    "totalSocialNumbersJ1Segments": 0,
    "totalSocialNumbersJ2Segments": 0,
    "totalDatesBirthAllSegments": 0,
    "totalDatesBirthBaseSegments": 0,
    "totalDatesBirthJ1Segments": 0,
    "totalDatesBirthJ2Segments": 0,
    "totalTelephoneNumbersAllSegments": 0
  }
}`

**What did you expect to see?**
I expect to get a valid metro2 file

**What did you see?**
1) I see errors like that (may vary depending on the json I pass there, but still errors)
 ./metro2 convert --format metro -g --input ./b.json b.metro2
Error: total_base_records in trailer record has a required field
2) However, the provided json converts into metro file. But the resulting metro file doesn't convert back into json.

**How can we reproduce the problem?**
1) Convert the json into metro, Now convert the result back to json.

**Comment by adamdecaf** [comment]
cc @mfdeveloper508 it looks like we aren't calculating `total_base_records` ?

**Comment by mfdeveloper508** [comment]
there is a problem of processing format string
so metro file had invalid file size, fixed the problem in PR 95
