### ISSUE TITLE
improper encoding 

### ISSUE THREAD

**Issue by Afzaluddintek** [moov-io/metro2#88]
Metro2 Version: moov/metro2:latest

**What were you trying to do?**
Convert Json to Metro2 using API call

**What did you expect to see?**
Converted response text in metro 2 format

**What did you see?**
Got the converted response but the encoding seems to be wrong. please find the attached screenshot for reference.

**How can we reproduce the problem?**
Run docker container using docker for windows.
Execute /convert API passing sample data.
Read the response and save in a file.
check file encoding.
![image](https://user-images.githubusercontent.com/66619563/151993917-820e70c5-534b-4d74-b395-9e283c2758b1.png)

**Comment by one10** [comment]
how do you know this encoding is broken? isn't the resulting file in binary format so it won't even render properly in many text editors?

**Comment by adamdecaf** [comment]
This sounds similar to https://github.com/moov-io/imagecashletter/issues/227. Can we get more information about your environment / request / response?

**Comment by mfdeveloper508** [comment]
Metro2 segments have 2 types character and packed
character segment is readable. but packed is not readable, looks like invalid encoding

Global function NewFile(string) is to specify segment type
convert function is using segment type of input file
New params added into convert command to avoid this problem

metro convert --help

Usage:
   convert [output] [flags]

Flags:
      --format string   format of metro file(required) (default "json")
  -g, --generate        generate trailer record
  -h, --help            help for convert
  -n, --newline         has new line (will use new line between records)
      --type string     file type (character or packed)

Global Flags:
      --input string   input file (default is $PWD/metro.json)
