### ISSUE TITLE
bureaus are asking for one record per line

### ISSUE THREAD

**Issue by one10** [moov-io/metro2#94]
Metro2 Version: `moov/metro2:latest` image id 1fd1f2e9b67e

**What were you trying to do?**
Generate any super-basic metro2 file with more than one user and furnish it to Experian

**What did you expect to see?**
Since all the validations passed I was expecting Experian to accept it for processing.

**What did you see?**
The feedback from Experian was:
There was an issue with the file you sent to us  and it couldn’t be processed. There is no Line Feed Characters (CRLF) to break the file into “clean” records. We cannot process files like this. We need you to fix and resend this file.

A similar issue was also reported twice by other Moov metro2 users in the Slack channel in the last few months:
https://moov-io.slack.com/archives/C014L9CAW77/p1637747898029500
https://moov-io.slack.com/archives/C014L9CAW77/p1648746025803759

**How can we reproduce the problem?**
Generate any valid metro2 file with more than one base record and observe the lack of Line Feed Characters

**Comment by mfdeveloper508** [comment]
Metro2 file has header record, trailer record, data record (base segment)
(*: each record has length field, this means that the new line don't put within a record)
We can add new line between each records (header, trailer, data)

**Comment by adamdecaf** [comment]
I don't see `\n`'s being added. Is this optional or somewhere else? 

https://github.com/moov-io/metro2/blob/f3131d715330af614c8b94d3b0ffafc4c5e8c4a8/pkg/file/file_instance.go#L262

**Comment by adamdecaf** [comment]
How was this working before? Is Experian requiring a newline, but other bureaus aren't?

**Comment by cushion-ci-user** [comment]
> How was this working before? Is Experian requiring a newline, but other bureaus aren't?

if you follow the first slack link, another person is reporting: "submitted a few files over to the 3 big agencies but Experian and Transunion are pushing back saying that the Metro 2 doc specifies that records should be on their own lines."

I can confirm Experian, haven't worked with the others.

**Comment by one10** [comment]
> How was this working before? Is Experian requiring a newline, but other bureaus aren't?

if you follow the first slack link, another person is reporting: "submitted a few files over to the 3 big agencies but Experian and Transunion are pushing back saying that the Metro 2 doc specifies that records should be on their own lines."

I can confirm Experian, haven't worked with the others.

**Comment by one10** [comment]
> We can add new line between each records (header, trailer, data)

what about CRLF between base records?

**Comment by mfdeveloper508** [comment]
https://github.com/moov-io/metro2/pull/95

**Comment by mfdeveloper508** [comment]
> I don't see `\n`'s being added. Is this optional or somewhere else?
> 
> https://github.com/moov-io/metro2/blob/f3131d715330af614c8b94d3b0ffafc4c5e8c4a8/pkg/file/file_instance.go#L262
> 
> Header doesn't seem to add a newline
> 
> https://github.com/moov-io/metro2/blob/f3131d715330af614c8b94d3b0ffafc4c5e8c4a8/pkg/lib/header_record.go#L126

https://github.com/moov-io/metro2/pull/95

**Comment by mfdeveloper508** [comment]
I reviewed specification for metro2
Eventually I don't find exact definition how to put all of records into a file

Here is similar definition for this (https://www.collect.org/cv11/Help/metro2format.html)
"This file has one long line of data for each account that is reported. It is actually made up of several segments."
According this, we can put all of the records into a line

Added new lines as following structure
[ie:]
HEADER
BASE DATA 1
BASE DATA 2
BASE DATA n ..
TRAILER

**Comment by adamdecaf** [comment]
Interesting.. We might have to add a config option to allow these on one line. Either way let's get the library output accepted by the bureaus.

**Comment by mfdeveloper508** [comment]
Added the option into convert command

metro convert --help

Usage:

convert [output] [flags]

Flags:
--format string format of metro file(required) (default "json")
-g, --generate generate trailer record
-h, --help help for convert
-n, --newline has new line (will use new line between records)
--type string file type (character or packed)

Global Flags:
--input string input file (default is $PWD/metro.json)
